package filey.app.core.ui.theme

import androidx.compose.ui.graphics.Color

val md_light_primary = Color(0xFF1565C0)
val md_light_onPrimary = Color(0xFFFFFFFF)
val md_light_primaryContainer = Color(0xFFD1E4FF)
val md_light_onPrimaryContainer = Color(0xFF001D36)
val md_light_secondary = Color(0xFF535F70)
val md_light_onSecondary = Color(0xFFFFFFFF)
val md_light_secondaryContainer = Color(0xFFD7E3F7)
val md_light_onSecondaryContainer = Color(0xFF101C2B)
val md_light_background = Color(0xFFFDFCFF)
val md_light_onBackground = Color(0xFF1A1C1E)
val md_light_surface = Color(0xFFFDFCFF)
val md_light_onSurface = Color(0xFF1A1C1E)
val md_light_surfaceVariant = Color(0xFFDFE2EB)
val md_light_onSurfaceVariant = Color(0xFF43474E)

val md_dark_primary = Color(0xFF9ECAFF)
val md_dark_onPrimary = Color(0xFF003258)
val md_dark_primaryContainer = Color(0xFF00497D)
val md_dark_onPrimaryContainer = Color(0xFFD1E4FF)
val md_dark_secondary = Color(0xFFBBC7DB)
val md_dark_onSecondary = Color(0xFF253140)
val md_dark_secondaryContainer = Color(0xFF3B4858)
val md_dark_onSecondaryContainer = Color(0xFFD7E3F7)
val md_dark_background = Color(0xFF1A1C1E)
val md_dark_onBackground = Color(0xFFE2E2E6)
val md_dark_surface = Color(0xFF1A1C1E)
val md_dark_onSurface = Color(0xFFE2E2E6)
val md_dark_surfaceVariant = Color(0xFF43474E)
val md_dark_onSurfaceVariant = Color(0xFFC3C7CF)
